title: The Quiet Animal
summary: From a fish in Nova Scotia to the priests of Eleusis to a patient at an ibogaine
  clinic, the long animal story of the search for quieter mind.
tags:
- psychedelics
- philosophy
- neuroscience
- animal-behavior
- addiction
author: Pumulo Sikaneta
published_at: '2026-05-08T10:15:25+00:00'
updated_at: '2026-05-08T12:15:13+00:00'
category: philosophy
